
// This file has been generated by the GUI designer. Do not modify.
namespace R7.Emblems
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.FileChooserButton filechooser1;
		private global::Gtk.RadioButton radioFile;
		private global::Gtk.RadioButton radioFolder;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.Table tableEmblems;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button buttonAbout;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button button3;
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget R7.Emblems.MainWindow
			this.Name = "R7.Emblems.MainWindow";
			this.Title = "";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child R7.Emblems.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.filechooser1 = new global::Gtk.FileChooserButton ("Select a Folder", ((global::Gtk.FileChooserAction)(2)));
			this.filechooser1.Name = "filechooser1";
			this.hbox2.Add (this.filechooser1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.filechooser1]));
			w1.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.radioFile = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("File"));
			this.radioFile.CanFocus = true;
			this.radioFile.Name = "radioFile";
			this.radioFile.DrawIndicator = true;
			this.radioFile.UseUnderline = true;
			this.radioFile.BorderWidth = ((uint)(6));
			this.radioFile.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox2.Add (this.radioFile);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.radioFile]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.radioFolder = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString("Folder"));
			this.radioFolder.CanFocus = true;
			this.radioFolder.Name = "radioFolder";
			this.radioFolder.DrawIndicator = true;
			this.radioFolder.UseUnderline = true;
			this.radioFolder.BorderWidth = ((uint)(6));
			this.radioFolder.Group = this.radioFile.Group;
			this.hbox2.Add (this.radioFolder);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.radioFolder]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.tableEmblems = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
			this.tableEmblems.Name = "tableEmblems";
			this.tableEmblems.RowSpacing = ((uint)(8));
			this.tableEmblems.ColumnSpacing = ((uint)(8));
			this.tableEmblems.BorderWidth = ((uint)(6));
			w5.Add (this.tableEmblems);
			this.GtkScrolledWindow.Add (w5);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w8.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.BorderWidth = ((uint)(6));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonAbout = new global::Gtk.Button ();
			this.buttonAbout.CanFocus = true;
			this.buttonAbout.Name = "buttonAbout";
			this.buttonAbout.UseUnderline = true;
			// Container child buttonAbout.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("About");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.buttonAbout.Add (w10);
			this.hbuttonbox2.Add (this.buttonAbout);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.buttonAbout]));
			w18.Expand = false;
			w18.Fill = false;
			this.hbox1.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbuttonbox2]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.Spacing = 10;
			this.hbuttonbox1.BorderWidth = ((uint)(6));
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseStock = true;
			this.button3.UseUnderline = true;
			this.button3.Label = "gtk-cancel";
			this.hbuttonbox1.Add (this.button3);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button3]));
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseStock = true;
			this.button2.UseUnderline = true;
			this.button2.Label = "gtk-ok";
			this.hbuttonbox1.Add (this.button2);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button2]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbuttonbox1]));
			w22.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 536;
			this.DefaultHeight = 344;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.filechooser1.SelectionChanged += new global::System.EventHandler (this.OnFilechooser1SelectionChanged);
			this.radioFile.Toggled += new global::System.EventHandler (this.OnRadioFileToggled);
			this.buttonAbout.Clicked += new global::System.EventHandler (this.OnButtonAboutClicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		}
	}
}
